In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("xlsx/ALLEGATO A QUIZ PATENTI NAUTICHE DD 131 DEL 31 MAGGIO 2022.xlsx")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2444 entries, 0 to 2443
Data columns (total 62 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   QUIZ BASE    2132 non-null   object
 1   Unnamed: 1   32 non-null     object
 2   Unnamed: 2   246 non-null    object
 3   Unnamed: 3   76 non-null     object
 4   Unnamed: 4   282 non-null    object
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   1718 non-null   object
 7   Unnamed: 7   1 non-null      float64
 8   Unnamed: 8   3 non-null      float64
 9   Unnamed: 9   0 non-null      float64
 10  Unnamed: 10  0 non-null      float64
 11  Unnamed: 11  77 non-null     object
 12  Unnamed: 12  1 non-null      float64
 13  Unnamed: 13  0 non-null      float64
 14  Unnamed: 14  1 non-null      float64
 15  Unnamed: 15  81 non-null     object
 16  Unnamed: 16  1 non-null      object
 17  Unnamed: 17  0 non-null      float64
 18  Unnamed: 18  0 non-null      float64
 19  Unnamed: 19  216 non-null    object
 20  Unnamed: 20  36 non-null     object
 21  Unnamed: 21  0 non-null      float64
 22  Unnamed: 22  1720 non-null   object
 23  Unnamed: 23  61 non-null     object
 24  Unnamed: 24  106 non-null    object
 25  Unnamed: 25  9 non-null      object
 26  Unnamed: 26  1718 non-null   object
 27  Unnamed: 27  2030 non-null   object
 28  Unnamed: 28  70 non-null     object
 29  Unnamed: 29  1 non-null      float64
 30  Unnamed: 30  1 non-null      float64
 31  Unnamed: 31  128 non-null    object
 32  Unnamed: 32  9 non-null      object
 33  Unnamed: 33  283 non-null    object
 34  Unnamed: 34  1 non-null      float64
 35  Unnamed: 35  30 non-null     object
 36  Unnamed: 36  2002 non-null   object
 37  Unnamed: 37  9 non-null      object
 38  Unnamed: 38  1779 non-null   object
 39  Unnamed: 39  30 non-null     object
 40  Unnamed: 40  0 non-null      float64
 41  Unnamed: 41  9 non-null      object
 42  Unnamed: 42  138 non-null    object
 43  Unnamed: 43  0 non-null      float64
 44  Unnamed: 44  1752 non-null   object
 45  Unnamed: 45  2061 non-null   object
 46  Unnamed: 46  282 non-null    object
 47  Unnamed: 47  0 non-null      float64
 48  Unnamed: 48  138 non-null    object
 49  Unnamed: 49  1718 non-null   object
 50  Unnamed: 50  0 non-null      float64
 51  Unnamed: 51  456 non-null    object
 52  Unnamed: 52  11 non-null     object
 53  Unnamed: 53  1718 non-null   object
 54  Unnamed: 54  174 non-null    object
 55  Unnamed: 55  61 non-null     object
 56  Unnamed: 56  282 non-null    object
 57  Unnamed: 57  36 non-null     object
 58  Unnamed: 58  1717 non-null   object
 59  Unnamed: 59  0 non-null      float64
 60  Unnamed: 60  61 non-null     object
 61  Unnamed: 61  282 non-null    object
dtypes: float64(19), object(43)
memory usage: 1.2+ MB

In [6]:
df.loc[1:, :].columns

Index(['QUIZ BASE', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Unnamed: 6', 'Unnamed: 7', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14', 'Unnamed: 15', 'Unnamed: 16', 'Unnamed: 17',
       'Unnamed: 18', 'Unnamed: 19', 'Unnamed: 20', 'Unnamed: 21',
       'Unnamed: 22', 'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25',
       'Unnamed: 26', 'Unnamed: 27', 'Unnamed: 28', 'Unnamed: 29',
       'Unnamed: 30', 'Unnamed: 31', 'Unnamed: 32', 'Unnamed: 33',
       'Unnamed: 34', 'Unnamed: 35', 'Unnamed: 36', 'Unnamed: 37',
       'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40', 'Unnamed: 41',
       'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44', 'Unnamed: 45',
       'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48', 'Unnamed: 49',
       'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52', 'Unnamed: 53',
       'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56', 'Unnamed: 57',
       'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60', 'Unnamed: 61'],
      dtype='object')

In [7]:
df.head()

,QUIZ BASE,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61
0,NaN,NaN,IMMAGINE,NaN,NaN,NaN,DOMANDA,NaN,NaN,NaN,...,NaN,TEMA,NaN,NaN,NaN,NaN,VOCE,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,Com'Ã¨ denominata la massima lunghezza dell'uni...,NaN,NaN,NaN,...,NaN,TEORIA DELLO SCAFO,NaN,NaN,NaN,NaN,Nomenclatura delle parti principali dello scafo,NaN,NaN,NaN
2,2,NaN,NaN,NaN,NaN,NaN,Cosa si intende per asse longitudinale di un'u...,NaN,NaN,NaN,...,NaN,TEORIA DELLO SCAFO,NaN,NaN,NaN,NaN,Nomenclatura delle parti principali dello scafo,NaN,NaN,NaN
3,3,NaN,NaN,NaN,NaN,NaN,Quale funzione svolge la sentina di un'unitÃ n...,NaN,NaN,NaN,...,NaN,TEORIA DELLO SCAFO,NaN,NaN,NaN,NaN,Nomenclatura delle parti principali dello scafo,NaN,NaN,NaN
4,4,NaN,NaN,NaN,NaN,NaN,Le murate sono:,NaN,NaN,NaN,...,NaN,TEORIA DELLO SCAFO,NaN,NaN,NaN,NaN,Nomenclatura delle parti principali dello scafo,NaN,NaN,NaN